### ISSUE TITLE
더시드봇 사용 관련 질문

### ISSUE THREAD

**Issue by cutekyb** [kiwitreekor/theseed-bot#4]
안녕하세요. 혹시 이 코드를 더시드엔진을 사용중인 [알파위키](https://awiki.theseed.io)의 계정에서도 적용해서 사용해도 될까요?

**Comment by cutekyb** [comment]
문서 훼손에 사용하는 등의 악용할 의도는 없습니다.

**Comment by cutekyb** [comment]
알파위키에 봇이 없어서, 아무래도 여러명이 많은 문서(역링크 정리 등)를 정리하기에는 한계가 있습니다.

**Comment by kiwitreekor** [comment]
라이선스만 준수하시면 상관 없습니다.
