### ISSUE TITLE
설치를 어떻게 해야 하는지 모르겠습니다..

### ISSUE THREAD

**Issue by Aapplemint** [kiwitreekor/theseed-bot#5]
![주석 2020-12-29 210616](https://user-images.githubusercontent.com/73971084/103282653-ce41f900-4a19-11eb-997e-e39d423e9b56.png)

봇 파일이 있는 곳에서 powershell 창을 열어 설치를 하려고 하면 저렇게 오류가 뜹니다. 뭐가 문제인가요? 설치법과 사용법 좀 자세히 알려주시면 감사하겠습니다 ㅜㅜ

**Comment by kiwitreekor** [comment]
먼저 python이 제대로 설치된 것이 맞는지 먼저 확인해보시기 바랍니다.
제대로 설치되었는데도 불구하고 저 현상이 다시 발생한다면 python -m pip install -r requirements.txt로 다시 시도해 보세요.
